### ISSUE TITLE
install guide

### ISSUE THREAD

**Issue by xclusive707** [sebastienvercammen/Pokemon-Go-Coords#1]
hey, thank you for the awesome release!

Can you maybe write a lil installguide for linux or windows nevermind...

best regards

**Comment by sebastienvercammen** [comment]
@xclusive707 I'll make sure to write a complete readme (including installation instructions) for the repo later tonight (GMT+1). Glad you like it.

**Comment by ImQuinton** [comment]
+1 would be amazing if a video tutorial came out, or any tutorial

**Comment by biiouii** [comment]
please help us thank you

**Comment by FaNNboii** [comment]
INSTALL GUIDE??

**Comment by sebastienvercammen** [comment]
@FaNNboii I've seen better ways of asking for an update.

I'm writing it. It takes time. In the meantime, feel free to learn how to code so you can catch up.

**Comment by tincampi** [comment]
INSTALL GUIDE?? INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??INSTALL GUIDE??

**Comment by sebastienvercammen** [comment]
Install guide added as readme in latest commit.
