### ISSUE TITLE
No API?

### ISSUE THREAD

**Issue by wpark6765** [sebastienvercammen/Pokemon-Go-Coords#10]
Can I get your API so I can implement it for my Discord channel. Thanks

**Comment by sebastienvercammen** [comment]
@wpark6765 There is currently no open API, but there is an on-going discussion about adding an API feed. If you want to share your thoughts, I'd love to hear them on the reddit thread: https://www.reddit.com/r/pokemongodev/comments/4vswda/pok%C3%A9spawns_realtime_feed_of_rare_pok%C3%A9mon_go/
