### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by nesttle** [sebastienvercammen/Pokemon-Go-Coords#2]
Hi folk! Nice work around here :)

Wondering how to connect to your website (no .json, no API found) to poll our Discord channel. We can crawl/scrap your site directly, but parsed info would be appreciated (less calls, less data, less load...).

Thanks in advance,

**Comment by sebastienvercammen** [comment]
@nesttle Would you like access to receive the data from my back-end bot, or would you like to be able to add your Discord as a source for data for my bot? Or both?

**Comment by Majesty01** [comment]
I am a little confused on how to set this up, i have web hosting set and i put the files in front end/public on the webhost but how to set the backend up? A tutorial would be nice

**Comment by sebastienvercammen** [comment]
@Majesty01 There is a readme in the last commit (which you can also view [on the project's GitHub page](https://github.com/sebastienvercammen/Pokemon-Go-Coords)).

This issue is also not the place to talk about this. If you have an issue, create a separate one.

**Comment by Miky94x** [comment]
@sebastienvercammen nice work, you can implement a Json page with an output like this: http://pastebin.com/FfFBdE0T
Keep the good work
Thanks

**Comment by sebastienvercammen** [comment]
@Miky94x No worries, I know how to implement an API :)

There's currently an on-going discussion about its implementation. I'd appreciate it if you could share your thoughts: https://www.reddit.com/r/pokemongodev/comments/4vswda/pok%C3%A9spawns_realtime_feed_of_rare_pok%C3%A9mon_go/
