### ISSUE TITLE
What is your discord channel? Where can I join it? n What is your bot actually do? 

### ISSUE THREAD

**Issue by boltux** [sebastienvercammen/Pokemon-Go-Coords#9]
I dont want to actually join your discord channel ı want just get cord n snipe pokemon bot, but ı guess without discord channel i can not do it, why n where i can find it?

**Comment by sebastienvercammen** [comment]
@boltux I don't own a Discord channel. I made this project to display all data on http://spawns.sebastienvercammen.be.

There is currently an on-going discussion about adding an API feed. If you want to share your thoughts, I'd love to hear them on the reddit thread: https://www.reddit.com/r/pokemongodev/comments/4vswda/pok%C3%A9spawns_realtime_feed_of_rare_pok%C3%A9mon_go/
